### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by StephenFluin** [adeora/playground#10] opened 2017-07-28 21:41 UTC
Bundle.js:301 Uncaught (in promise) Error: Could not load /dist/main.js: Cannot read property 'text' of undefined
    at Bundle.js:301
    at <anonymous>

on 

https://angular-sandbox-f4192.firebaseapp.com/#,nVRRb9MwEP4rR17SSk0iEE9ZVm1DQiCxIU1DPBAe3NhNXBxfZDvtStX_zjluSrcOJGgemtjffd_5uzvvoqzCtkMttEudjfJI0pdxsLsxuLHC3CLvldjD0mAL8RXTda.YyTrF3BJNmywCLL4o9Rj5biScwV0d4mdw3XVKVsxJ1PdiecZXoRGeo9TicWCpFLMWPgiDsAPJc9B9uxDmAjRrRQ7WGalr2PsI_1wdRSe7UgNYoUTl0OQQN0IpTDZoFE9Y18Uzv.9E648gvhiVQxmlJy40rlVlRKj99CwbYvrqiY5qlBwMev1iRYKe6waxjCh6SGs0IGQVHLI5fHvi7vchJS5IxQwOecQLYgFHL2Z7XPsrdIHoyCnW_QH0whlvmdQhK9gNhwD6RbNIai4eB2.oRwr_P_d7RSMYnwdU8SpJwhvAQyNgIRRuwFZGds7CRipFS9AZXEsuOEgNjlByaaiiQM0EW.xTH2lo1YLGkUwLgjsExrkPaSk0DXtJMvc2j.pFEAO37cRlGTnx6LIVW7Ow7KsSCK2pLuPGuc7mWdbr7kedUv2HJkxW9upN.jZ9nVVKkkeZbWSbtqS4svG8yALVfBD.H9kyOtf9SdUg.oxL68aPMjoTK7Kj2cUC.XbM4FmDz0e5T8g4DUmaHszy8efIIjtw0fZY1aHiWUutEO6E37MN4.AfGhj.6WY46a67.j3zA7o9MpzOoK6XYTfcCRWNBCqRKqwn8X2vtZ_9688P4COkEjyeEu5ZapNpeuz_oHlQnLyQhY8_nPvpTUCn_wgK1zQOu8OQ7_dgEdq.aqL9Lw

**Steps to reproduce:**
1. https://edit.ng
1. Rewrite templates/template.html to point to component.html
1. Create component.html
1. Delete template.html
1. Click Compile

**Comment by adeora** [comment] 2017-07-28 22:04
@StephenFluin Bug was caused by an outdated browser compiler bundle. Should be fixed on https://edit.ng. Can you confirm?

**Comment by adeora** [comment] 2017-07-28 22:06
87bc576 should fix. If issue fixed on edit.ng, will close.

**Closed as completed** 2017-07-31 21:06 UTC
Labels: bug
